import {
  UCLAW_COMPATIBILITY_PROVIDER_ID,
  UCLAW_DEFAULT_API_PROTOCOL,
  UCLAW_DEFAULT_MODEL,
  UCLAW_LEGACY_AUTH_ACCOUNT_IDS,
  UCLAW_LEGACY_PROVIDER_IDS,
  UCLAW_MANAGED_ACCOUNT_ID,
  UCLAW_MANAGED_AUTH_ACCOUNT_ID,
  UCLAW_MANAGED_PROVIDER_BASE_URL,
  UCLAW_MANAGED_PROVIDER_ID,
  UCLAW_PROVIDER_REQUEST_TIMEOUT_SECONDS,
  UCLAW_PRODUCTION_ORIGIN,
  UCLAW_RUNTIME_CONTRACT_VERSION,
} from '../../shared/junfeiai-endpoints';

export {
  UCLAW_AUTH_REQUEST_TIMEOUT_MS,
  UCLAW_BOOTSTRAP_REQUEST_TIMEOUT_MS,
  UCLAW_COMPACTION_MODE,
  UCLAW_COMPACTION_RESERVE_TOKENS_FLOOR,
  UCLAW_DEFAULT_ACCESS_TOKEN_LIFETIME_SECONDS,
  UCLAW_DEFAULT_MODEL_CONTEXT_WINDOW,
  UCLAW_DEFAULT_THINKING_LEVEL,
  UCLAW_EXEC_ASK,
  UCLAW_EXEC_SECURITY,
  UCLAW_IMAGE_GENERATION_DEFAULT_SIZE,
  UCLAW_IMAGE_GENERATION_TIMEOUT_MS,
  UCLAW_MEDIA_GENERATION_CLIENT_TIMEOUT_BUFFER_MS,
  UCLAW_MEDIA_GENERATION_TEST_TIMEOUT_MS,
  UCLAW_MANAGED_SERVICE_NAME,
  UCLAW_OFFLINE_GRACE_SECONDS,
  UCLAW_RELAY_REQUEST_TIMEOUT_MS,
  UCLAW_TOKEN_REFRESH_SKEW_SECONDS,
  UCLAW_VERIFICATION_REQUEST_TIMEOUT_MS,
  UCLAW_VERIFY_MEMORY_CACHE_SECONDS,
  UCLAW_VIDEO_GENERATION_MAX_DOWNLOAD_BYTES,
  UCLAW_VIDEO_GENERATION_POLL_INTERVAL_MS,
  UCLAW_VIDEO_GENERATION_PREFERRED_RESOLUTION,
  UCLAW_VIDEO_GENERATION_PREFERRED_SHORT_EDGE,
  UCLAW_VIDEO_GENERATION_TIMEOUT_MS,
} from '../../shared/junfeiai-endpoints';

export const UCLAW_PROVIDER_ID = UCLAW_MANAGED_PROVIDER_ID;
export const UCLAW_ACCOUNT_ID = UCLAW_MANAGED_ACCOUNT_ID;
export const UCLAW_AUTH_ACCOUNT_ID = UCLAW_MANAGED_AUTH_ACCOUNT_ID;
export const UCLAW_DEFAULT_BASE_URL = UCLAW_MANAGED_PROVIDER_BASE_URL;
export const UCLAW_PROVIDER_TIMEOUT_SECONDS = UCLAW_PROVIDER_REQUEST_TIMEOUT_SECONDS;

export function normalizeUclawModelContextWindow(value: unknown): number | undefined {
  return typeof value === 'number' && Number.isFinite(value) && value > 0
    ? value
    : undefined;
}

export function getUclawBackendOrigin(): string {
  return UCLAW_PRODUCTION_ORIGIN;
}

export function getUclawProviderBaseUrl(): string {
  return UCLAW_MANAGED_PROVIDER_BASE_URL;
}

export function getUclawDefaultBaseUrl(): string {
  return UCLAW_DEFAULT_BASE_URL;
}

export function isUclawManagedDistribution(): boolean {
  if (process.env.CLAWX_MANAGED_PROVIDER === '1') {
    return true;
  }
  if (process.env.CLAWX_MANAGED_PROVIDER === '0') {
    return false;
  }
  if (process.env.CLAWX_E2E === '1') {
    return false;
  }
  return true;
}

export {
  UCLAW_COMPATIBILITY_PROVIDER_ID,
  UCLAW_DEFAULT_API_PROTOCOL,
  UCLAW_DEFAULT_MODEL,
  UCLAW_LEGACY_AUTH_ACCOUNT_IDS,
  UCLAW_LEGACY_PROVIDER_IDS,
  UCLAW_MANAGED_ACCOUNT_ID,
  UCLAW_MANAGED_PROVIDER_BASE_URL,
  UCLAW_MANAGED_PROVIDER_ID,
  UCLAW_PROVIDER_REQUEST_TIMEOUT_SECONDS,
  UCLAW_PRODUCTION_ORIGIN,
  UCLAW_RUNTIME_CONTRACT_VERSION,
};
