import { JUNFEIAI_IMAGE_GENERATION_DEFAULT_MODEL } from '../../shared/junfeiai-endpoints';

export const CLAWX_OPENAI_IMAGE_PROVIDER_KEY = 'clawx-openai-image';
export const CLAWX_OPENAI_IMAGE_DEFAULT_MODEL = JUNFEIAI_IMAGE_GENERATION_DEFAULT_MODEL;
export const CLAWX_OPENAI_IMAGE_DEFAULT_REF = `${CLAWX_OPENAI_IMAGE_PROVIDER_KEY}/${CLAWX_OPENAI_IMAGE_DEFAULT_MODEL}`;
